### ISSUE TITLE
add ability to crud stories

### ISSUE THREAD

**Issue by madhums** [compassionprojects/socialchange#10]
- [ ] keep "policy change" as overarching goal while designing projects
- [x] create project
- [x] edit project
- [x] delete project
- [x] show project
- [x] upload documents/photos
- [x] crud followups/updates
