### ISSUE TITLE
add notifications

### ISSUE THREAD

**Issue by madhums** [compassionprojects/socialchange#44]
Users should be able to subscribe to get notified when a new discussion, story update or a new post is created for a story/discussion.

```
subscriptions:
--------------
story
discussion
user
subscribed_to: new_discussions | new_posts | new_story_updates
```

We need to provide a notification preferences page where user is able to set preferences. 
For the subscriptions, the page should list the story / discussion user is subscribed to and must give an option to unsubscribe. 

**Todo:**

Preferences:
- [x] add user preferences migration, model and tests
- [x] create user preference once user confirms his account
- [x] add user preferences page

Notifications:

- [x] add noticed gem
- [x] create models for story, discussion and post notifications
- [x] create email templates
- [ ] add translations
- [x] display notifications in the UI 
  - [x] show unread notifications indicator
